version: "3.9"
services:
    middletier:
        depends_on: 
            - web
            - redis
        restart: always
        build: ./middletier
        ports:
            - "4000:4000"
        environment: 
            WEB_URL: "http://web:5000"
            REDIS_HOST: "redis"
            NODE_ENV: "development"
    web:
        depends_on:
            - db
        restart: always
        build: ./chii
        ports:
            - "5000:5000"
        environment:
            AZURE_FILESHARE_CONNECTIONSTRING: ""
            AZURE_SQL_BANGUMIDB_CONNECTIONSTRING: ""
            ASPNETCORE_ENVIRONMENT: "Development"
            ASPNETCORE_URLS: "http://0.0.0.0:5000"
    db:
        image: "postgres:13"
        restart: always
        volumes:
            - ./dbinit/:/docker-entrypoint-initdb.d
        environment: 
            POSTGRES_PASSWORD: password
            POSTGRES_DB: bangumi
    redis:
        image: "redis:6"
        restart: always
