version: "3"
services:
    web:
        depends_on:
            - db
        restart: always
        build: ./chii
        ports:
            - "3001:5000"
        environment:
            AZURE_FILESHARE_CONNECTIONSTRING: ""
            AZURE_SQL_BANGUMIDB_CONNECTIONSTRING: ""
            ASPNETCORE_ENVIRONMENT: "Development"
            ASPNETCORE_URLS: "http://0.0.0.0:5000"
    db:
        image: "postgres:13"
        restart: always
        volumes:
            - ./dbinit/:/docker-entrypoint-initdb.d
        environment: 
            POSTGRES_PASSWORD: password
            POSTGRES_DB: bangumi
        ports:
            - "5555:5432"
