// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using chii.Models;

namespace chii.Migrations
{
    [DbContext(typeof(BangumiContext))]
    [Migration("20220403041717_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("chii.Models.CustomRank", b =>
                {
                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<int>("SciRank")
                        .HasColumnType("integer");

                    b.HasKey("SubjectId");

                    b.ToTable("CustomRanks");
                });

            modelBuilder.Entity("chii.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("CollectCount")
                        .HasColumnType("integer");

                    b.Property<int>("DoCount")
                        .HasColumnType("integer");

                    b.Property<int>("DroppedCount")
                        .HasColumnType("integer");

                    b.Property<int>("FavCount")
                        .HasColumnType("integer");

                    b.Property<string>("Infobox")
                        .HasColumnType("json");

                    b.Property<bool>("NSFW")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.Property<string>("NameCN")
                        .HasColumnType("varchar(80)");

                    b.Property<int>("OnHoldCount")
                        .HasColumnType("integer");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<int?>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("RateCount")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<int>("WishCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("chii.Models.SubjectEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Alias")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedAlias")
                        .HasColumnType("text");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedAlias");

                    b.HasIndex("SubjectId");

                    b.ToTable("SubjectEntities");
                });

            modelBuilder.Entity("chii.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedContent")
                        .HasColumnType("text");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<int>("UserCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId", "NormalizedContent")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("chii.Models.Timestamp", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Date");

                    b.ToTable("Timestamps");
                });

            modelBuilder.Entity("chii.Models.CustomRank", b =>
                {
                    b.HasOne("chii.Models.Subject", "Subject")
                        .WithOne("ScientificRank")
                        .HasForeignKey("chii.Models.CustomRank", "SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("chii.Models.SubjectEntity", b =>
                {
                    b.HasOne("chii.Models.Subject", "Subject")
                        .WithMany("SubjectEntities")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("chii.Models.Tag", b =>
                {
                    b.HasOne("chii.Models.Subject", "Subject")
                        .WithMany("Tags")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("chii.Models.Subject", b =>
                {
                    b.Navigation("ScientificRank");

                    b.Navigation("SubjectEntities");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
