--
-- PostgreSQL database dump
--

-- Dumped from database version 13.3 (Debian 13.3-1.pgdg100+1)
-- Dumped by pg_dump version 13.3

-- Started on 2021-06-30 21:04:40 CST
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 202 (class 1259 OID 16425)
-- Name: CustomRanks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."CustomRanks" (
    "SubjectId" integer NOT NULL,
    "SciRank" integer NOT NULL,
    "Date" timestamp without time zone NOT NULL
);


ALTER TABLE public."CustomRanks" OWNER TO postgres;

--
-- TOC entry 201 (class 1259 OID 16417)
-- Name: Subjects; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Subjects" (
    "Id" integer NOT NULL,
    "Name" character varying(500) NOT NULL,
    "NameCN" character varying(500),
    "Type" character varying(10) NOT NULL,
    "Rank" integer,
    "Date" timestamp without time zone,
    "Votenum" integer NOT NULL,
    "Favnum" integer NOT NULL
);


ALTER TABLE public."Subjects" OWNER TO postgres;

--
-- TOC entry 204 (class 1259 OID 16437)
-- Name: Tags; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Tags" (
    "Id" integer NOT NULL,
    "SubjectId" integer NOT NULL,
    "Content" character varying(500),
    "TagCount" integer NOT NULL,
    "UserCount" integer NOT NULL,
    "Confidence" double precision NOT NULL
);


ALTER TABLE public."Tags" OWNER TO postgres;

--
-- TOC entry 203 (class 1259 OID 16435)
-- Name: Tags_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Tags" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Tags_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 200 (class 1259 OID 16412)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 2822 (class 2606 OID 16429)
-- Name: CustomRanks PK_CustomRanks; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CustomRanks"
    ADD CONSTRAINT "PK_CustomRanks" PRIMARY KEY ("SubjectId");


--
-- TOC entry 2820 (class 2606 OID 16424)
-- Name: Subjects PK_Subjects; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Subjects"
    ADD CONSTRAINT "PK_Subjects" PRIMARY KEY ("Id");


--
-- TOC entry 2825 (class 2606 OID 16444)
-- Name: Tags PK_Tags; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tags"
    ADD CONSTRAINT "PK_Tags" PRIMARY KEY ("Id");


--
-- TOC entry 2818 (class 2606 OID 16416)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 2823 (class 1259 OID 16450)
-- Name: IX_Tags_SubjectId_Content; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Tags_SubjectId_Content" ON public."Tags" USING btree ("SubjectId", "Content");


--
-- TOC entry 2826 (class 2606 OID 16430)
-- Name: CustomRanks FK_CustomRanks_Subjects_SubjectId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CustomRanks"
    ADD CONSTRAINT "FK_CustomRanks_Subjects_SubjectId" FOREIGN KEY ("SubjectId") REFERENCES public."Subjects"("Id") ON DELETE CASCADE;


--
-- TOC entry 2827 (class 2606 OID 16445)
-- Name: Tags FK_Tags_Subjects_SubjectId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tags"
    ADD CONSTRAINT "FK_Tags_Subjects_SubjectId" FOREIGN KEY ("SubjectId") REFERENCES public."Subjects"("Id") ON DELETE CASCADE;


-- Completed on 2021-06-30 21:04:40 CST

--
-- PostgreSQL database dump complete
--

