apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-standard-retain
  resources:
    requests:
      storage: 5Gi
status: {}