apiVersion: v1
kind: Service
metadata:
  labels:
    service: middletier
  name: middletier
spec:
  type: NodePort
  ports:
    - name: "4000"
      port: 4000
      targetPort: 4000
  selector:
    service: middletier
status:
  loadBalancer: {}