apiVersion: v1
kind: Service
metadata:
  labels:
    service: web
  name: web
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    service: web
status:
  loadBalancer: {}
