name: Build and push backend image

on:
  push:
    branches:
      - main
    paths:
      - 'chii/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get current version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master
      with:
        path: chii/
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: wattlebird
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./chii
        push: true
        tags: wattlebird/chii_backend:latest, wattlebird/chii_backend:${{ steps.package-version.outputs.current-version}}
